backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "video"
    label: "Video"
    folder: "src/video"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Video Source", name: "vidSource", widget: "file" }
      - { label: "Runtime Seconds", name: "runtimeMinutes", widget: "string" }
      - { label: "Runtime Seconds", name: "runtimeSeconds", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
  - name: "researchAndPub"
    label: "Research and Pulblication Link"
    folder: "src/researchAndPub"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "URL", name: "link", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
  - name: "work"
    label: "Work History"
    folder: "src/work"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Start Year", name: "startYear", widget: "string" }
      - { label: "End Year", name: "endYear", widget: "string" }
  - name: "galleryImage"
    label: "Gallery Image"
    folder: "src/galleryImage"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Caption", name: "caption", widget: "string" }
      - { label: "Image Source", name: "imageSource", widget: "image" }
  - name: "homeSplashHeader"
    label: "Home Splash Header"
    folder: "src/homeSplashHeader"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Text", name: "text", widget: "string" }
  - name: "homeSplashDescription"
    label: "Home Splash Description"
    folder: "src/homeSplashDescription"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Text", name: "text", widget: "string" }
  - name: "homeSplashFooter"
    label: "Home Splash Footer"
    folder: "src/homeSplashFooter"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Word One", name: "wordOne", widget: "string" }
      - { label: "Word Two", name: "wordTwo", widget: "string" }
      - { label: "Word three", name: "wordThree", widget: "string" }
  - name: "aboutSection"
    label: "About Section"
    folder: "src/aboutSection"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "About Text", name: "text", widget: "markdown" }
  - name: "portfolioSection"
    label: "Portfolio Section"
    folder: "src/portfolioSection"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Text", name: "text", widget: "text" }
