backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "video"
    label: "Video"
    folder: "src/video"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Video Source", name: "vidSource", widget: "file" }
      - { label: "Runtime Seconds", name: "runtimeMinutes", widget: "string" }
      - { label: "Runtime Seconds", name: "runtimeSeconds", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
  - name: "researchAndPub"
    label: "Research and Pulblication Link"
    folder: "src/researchAndPub"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "URL", name: "link", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
  - name: "work"
    label: "Work History"
    folder: "src/work"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Start Year", name: "startYear", widget: "string" }
      - { label: "End Year", name: "endYear", widget: "string" }
  - name: "galleryImage"
    label: "Gallery Image"
    folder: "src/galleryImage"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Caption", name: "caption", widget: "string" }
      - { label: "Image Source", name: "imageSource", widget: "image" }
  - name: "headshot"
    label: "Headshot Image"
    folder: "src/headshot"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Image Source", name: "imageSource", widget: "image" }
  - name: "aboutSection"
    label: "About Section"
    folder: "src/aboutSection"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "About Text", name: "body", widget: "markdown" }
  - name: "siteTextContent"
    label: "Site Text Content"
    folder: "src/siteTextContent"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - {
          label: "Home Splash Header",
          name: "homeSplashHeader",
          widget: "string",
        }
      - {
          label: "Home Splash Description",
          name: "homeSplashDescription",
          widget: "string",
        }
      - { label: "Splash Footer Text One", name: "textOne", widget: "string" }
      - { label: "Splash Footer Text Two", name: "textTwo", widget: "string" }
      - {
          label: "Splash Footer Text Three",
          name: "textThree",
          widget: "string",
        }
      - {
          label: "Portfolio Section",
          name: "portfolioSectionText",
          widget: "text",
        }
      - {
          label: "Accordion One Heading (Videos)",
          name: "accordionOneHeading",
          widget: "text",
        }
      - {
          label: "Accordion Two Heading (Text Links)",
          name: "accordionTwoHeading",
          widget: "text",
        }
      - {
          label: "Accordion Three Heading (Work History)",
          name: "accordionThreeHeading",
          widget: "text",
        }
      - {
          label: "Gallery Splash Header",
          name: "gallerySplashHeader",
          widget: "string",
        }
      - {
          label: "Gallery Splash Description",
          name: "gallerySplashDescription",
          widget: "string",
        }
      - { label: "Contact Section", name: "contactSectionText", widget: "text" }
  - name: "socialAndEmail"
    label: "Social and Email"
    folder: "src/socialAndEmail"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "LinkedIn", name: "linkedIn", widget: "text" }
      - { label: "Twitter", name: "twitter", widget: "text" }
      - { label: "Email", name: "email", widget: "text" }
